### PR TITLE
merge 

### PR DESCRIPTION
**Pull request by jianhong**
change version.txt to versions.yml;
remove `paste` command from igv.nf;
fix the bug that annopeaks.r does not creat folder;

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/hicar/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/hicar _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jianhong** [comment]
I updated the bwa/index module and created a PR at [#1040](https://github.com/nf-core/modules/pull/1040)

**Comment by ewels** [comment]
Pull reuqests from your fork need to be made against the `dev` branch, not `master` as you did here. Once merged we can then create a second pull request to `master`. Sorry for the additional step.

**Comment by ewels** [comment]
Ok, I updated this to point to `dev`. As soon as you push a new commit the tests should pass.

**Comment by jianhong** [comment]
> Ok, I updated this to point to `dev`. As soon as you push a new commit the tests should pass.

Thank you for that.

**Pull request merged**
