### PR TITLE
Dev remove getscale

### PR DESCRIPTION
**Pull request by jianhong**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/hicar/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/hicar _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jianhong** [comment]
@Emiller88 Did I understand you correctly about this? Does subworkflow work?

**Comment by edmundmiller** [comment]
I was just asking whether it needed to be its own process. If it was computationally intensive or not (which it should just be some quick calculations), because that would be a lot of overhead in the cloud or just extra jobs to submit in slurm.

**Comment by jianhong** [comment]
> I was just asking whether it needed to be its own process. If it was computationally intensive or not (which it should just be some quick calculations), because that would be a lot of overhead in the cloud or just extra jobs to submit in slurm.

I suppose the this subworkflow will not submit any job. Correct me if I mis-understand about this. I keep this sub-workflow because it will be called by several different steps.

**Comment by edmundmiller** [comment]
> I suppose the this subworkflow will not submit any job. Correct me if I mis-understand about this. I keep this sub-workflow because it will be called by several different steps.

Hmm, makes sense! Maybe it needs an `executor 'local'` defined in the process?

**Pull request closed without merging**
